# Generated by Django 2.2.7 on 2019-12-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieW', '0002_auto_20191124_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcast',
            fields=[
                ('castid', models.AutoField(primary_key=True, serialize=False)),
                ('castname', models.CharField(max_length=100)),
                ('castimage', models.BinaryField()),
            ],
            options={
                'db_table': 'tblcast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldirectors',
            fields=[
                ('directorid', models.AutoField(primary_key=True, serialize=False)),
                ('directorname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbldirectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmovies',
            fields=[
                ('movieid', models.IntegerField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=100)),
                ('moviedirector', models.CharField(max_length=100)),
                ('moviestudio', models.CharField(max_length=100)),
                ('movieyear', models.DateField()),
                ('moviecast', models.CharField(max_length=100)),
                ('movieproducer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblmovies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbluser',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('passwordenc', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('dateofjoining', models.DateField()),
                ('dateofbirth', models.DateField()),
                ('userlevel', models.TextField(blank=True, db_column='UserLevel', null=True)),
            ],
            options={
                'db_table': 'tbluser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcasts',
            fields=[
                ('castid', models.AutoField(primary_key=True, serialize=False)),
                ('castname', models.CharField(max_length=100)),
                ('castimage', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
