# Generated by Django 2.2.7 on 2019-12-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieW', '0004_auto_20191206_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcasts',
            name='castimage',
        ),
    ]
