# Generated by Django 2.2.7 on 2019-12-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieW', '0005_remove_tblcasts_castimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tblcasts',
            new_name='tblpartypop',
        ),
    ]
