# Generated by Django 2.2.7 on 2019-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieW', '0006_auto_20191206_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblimagetest',
            fields=[
                ('castid', models.AutoField(primary_key=True, serialize=False)),
                ('castname', models.CharField(max_length=100)),
                ('castimage', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='tblpartypop',
        ),
    ]
