# Generated by Django 2.2.7 on 2019-12-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieW', '0007_auto_20191206_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tblimagetest',
        ),
    ]
