# Generated by Django 2.2.7 on 2019-12-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieW', '0008_delete_tblimagetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblcastimage',
            fields=[
                ('castid', models.AutoField(primary_key=True, serialize=False)),
                ('castname', models.CharField(max_length=100)),
                ('castimage', models.FileField(default='', upload_to='images/')),
            ],
        ),
    ]
