# Generated by Django 2.2.7 on 2019-12-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieW', '0009_tblcastimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tblcastimage',
            new_name='Tblcast',
        ),
    ]
