# Generated by Django 2.2.7 on 2019-12-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieW', '0010_auto_20191206_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcast',
            name='castimage',
            field=models.FileField(default='', upload_to='castimages/'),
        ),
    ]
